export const APIKEY = 'JgEbWxgFwhWVfUfVArF9AH6sl6E1VlNN';
export const SET_HEADLINE = 'SET_HEADLINE';
export const SET_CURRENT_CONDITIONS = 'SET_CURRENT_CONDITIONS';
export const SET_HOURLY_FORECAST = 'SET_HOURLY_FORECAST';
export const SET_DAILY_FORECAST  = 'SET_DAILY_FORECAST';